# .golangci.yml - 代码质量配置
run:
  timeout: 5m
  skip-dirs:
    - vendor
    - third_party

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/your-org/golang-2025 # 请替换为您的项目路径
  govet:
    check-shadowing: true
  misspell:
    locale: US
  gocyclo:
    min-complexity: 15
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    hhecks: ["all"]
  revive:
    confidence: 0.8
    rules:
      - name: package-comments
        disabled: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - gosimple
    - unconvert
    - ineffassign
    - misspell
    - errcheck
    - revive
    - gocyclo
    - typecheck
    - unused
  disable:
    - maligned
    - goconst
    - gochecknoinits

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - funlen
        - gocyclo

# 输出格式
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 