# golangci-lint 配置
# 2024 最佳实践配置

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # 默认启用
    - errcheck      # 检查未处理的错误
    - gosimple      # 简化代码
    - govet         # 标准 go vet 检查
    - ineffassign   # 检测无效赋值
    - staticcheck   # 静态分析
    - unused        # 检测未使用的代码

    # 额外启用
    - gofmt         # 格式检查
    - goimports     # import 检查
    - misspell      # 拼写检查
    - revive        # 代码规范
    - gosec         # 安全检查
    - gocritic      # 代码评审
    - gocyclo       # 圈复杂度
    - dupl          # 重复代码检测
    - bodyclose     # HTTP body 关闭检查
    - noctx         # Context 使用检查
    - unparam       # 未使用参数检查
    - prealloc      # 切片预分配
    - nakedret      # naked return 检查
    - godot         # 注释句点检查
    - whitespace    # 空白字符检查
    - wsl           # 空行检查

  disable:
    - typecheck     # 由于使用了泛型，可能会误报

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - whyNoLint
      - unnamedResult

  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # 允许某些错误不处理
      - G307  # 允许某些 defer 不检查错误

issues:
  exclude-rules:
    # 排除测试文件的某些检查
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec

    # 排除生成的代码
    - path: (^|/)vendor/
      linters:
        - all
    - path: \.pb\.go$
      linters:
        - all
    - path: _gen\.go$
      linters:
        - all
    - path: wire_gen\.go$
      linters:
        - all

    # 排除某些常见的误报
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec
    - text: "ST1000: at least one file in a package should have a package comment"
      linters:
        - stylecheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
