# Codecov 配置文件
# 参考: https://docs.codecov.com/docs/codecov-yaml

codecov:
  # 要求覆盖率
  require_ci_to_pass: yes

  # 通知配置
  notify:
    wait_for_ci: yes

# 覆盖率配置
coverage:
  # 精度
  precision: 2

  # 范围
  range: "70...100"

  # 状态
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: auto
        branches:
          - main
          - develop
    patch:
      default:
        target: 60%
        threshold: 1%
        base: auto

# 忽略的文件和目录
ignore:
  - ".*\\.pb\\.go$"
  - ".*\\.gen\\.go$"
  - ".*_wire_gen\\.go$"
  - ".*_mock\\.go$"
  - "cmd/.*"
  - "examples/.*"
  - "tools/.*"
  - "deployments/.*"
  - "docs/.*"
  - "migrations/.*"
  - "test/.*"
  - "scripts/.*"

# 注释配置
comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: no
