codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error
    
    patch:
      default:
        target: 80%
        threshold: 10%
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "examples/**"
  - "scripts/**"
  - "docs/**"
  - "archive/**"
  - "docs_old/**"
  - "reports/**"

