// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: internal/interfaces/grpc/proto/health.proto

package healthpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_interfaces_grpc_proto_health_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_interfaces_grpc_proto_health_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_health_proto_rawDescGZIP(), []int{0, 0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=health.v1.HealthResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_interfaces_grpc_proto_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_proto_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

var File_internal_interfaces_grpc_proto_health_proto protoreflect.FileDescriptor

const file_internal_interfaces_grpc_proto_health_proto_rawDesc = "" +
	"\n" +
	"+internal/interfaces/grpc/proto/health.proto\x12\thealth.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x7f\n" +
	"\x0eHealthResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .health.v1.HealthResponse.StatusR\x06status\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022K\n" +
	"\rHealthService\x12:\n" +
	"\x05Check\x12\x16.google.protobuf.Empty\x1a\x19.health.v1.HealthResponseBHZFgithub.com/yourusername/golang/internal/interfaces/grpc/proto/healthpbb\x06proto3"

var (
	file_internal_interfaces_grpc_proto_health_proto_rawDescOnce sync.Once
	file_internal_interfaces_grpc_proto_health_proto_rawDescData []byte
)

func file_internal_interfaces_grpc_proto_health_proto_rawDescGZIP() []byte {
	file_internal_interfaces_grpc_proto_health_proto_rawDescOnce.Do(func() {
		file_internal_interfaces_grpc_proto_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_interfaces_grpc_proto_health_proto_rawDesc), len(file_internal_interfaces_grpc_proto_health_proto_rawDesc)))
	})
	return file_internal_interfaces_grpc_proto_health_proto_rawDescData
}

var file_internal_interfaces_grpc_proto_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_interfaces_grpc_proto_health_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_interfaces_grpc_proto_health_proto_goTypes = []any{
	(HealthResponse_Status)(0), // 0: health.v1.HealthResponse.Status
	(*HealthResponse)(nil),     // 1: health.v1.HealthResponse
	(*emptypb.Empty)(nil),      // 2: google.protobuf.Empty
}
var file_internal_interfaces_grpc_proto_health_proto_depIdxs = []int32{
	0, // 0: health.v1.HealthResponse.status:type_name -> health.v1.HealthResponse.Status
	2, // 1: health.v1.HealthService.Check:input_type -> google.protobuf.Empty
	1, // 2: health.v1.HealthService.Check:output_type -> health.v1.HealthResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_interfaces_grpc_proto_health_proto_init() }
func file_internal_interfaces_grpc_proto_health_proto_init() {
	if File_internal_interfaces_grpc_proto_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_interfaces_grpc_proto_health_proto_rawDesc), len(file_internal_interfaces_grpc_proto_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_interfaces_grpc_proto_health_proto_goTypes,
		DependencyIndexes: file_internal_interfaces_grpc_proto_health_proto_depIdxs,
		EnumInfos:         file_internal_interfaces_grpc_proto_health_proto_enumTypes,
		MessageInfos:      file_internal_interfaces_grpc_proto_health_proto_msgTypes,
	}.Build()
	File_internal_interfaces_grpc_proto_health_proto = out.File
	file_internal_interfaces_grpc_proto_health_proto_goTypes = nil
	file_internal_interfaces_grpc_proto_health_proto_depIdxs = nil
}
