// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/interfaces/grpc/proto/health.proto

package healthpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_interfaces_grpc_proto_health_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_interfaces_grpc_proto_health_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// HealthResponse 健康检查响应
type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status HealthResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=health.v1.HealthResponse_Status" json:"status,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_grpc_proto_health_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_grpc_proto_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

var File_internal_interfaces_grpc_proto_health_proto protoreflect.FileDescriptor

var file_internal_interfaces_grpc_proto_health_proto_rawDesc = []byte{
	// Placeholder - would be generated by protoc
}

var file_internal_interfaces_grpc_proto_health_proto_rawDescOnce sync.Once
var file_internal_interfaces_grpc_proto_health_proto_rawDescData = file_internal_interfaces_grpc_proto_health_proto_rawDesc

func file_internal_interfaces_grpc_proto_health_proto_rawDescGZIP() []byte {
	file_internal_interfaces_grpc_proto_health_proto_rawDescOnce.Do(func() {
		file_internal_interfaces_grpc_proto_health_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_interfaces_grpc_proto_health_proto_rawDescData)
	})
	return file_internal_interfaces_grpc_proto_health_proto_rawDescData
}

var file_internal_interfaces_grpc_proto_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_interfaces_grpc_proto_health_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_interfaces_grpc_proto_health_proto_goTypes = []interface{}{
	(HealthResponse_Status)(0), // 0: health.v1.HealthResponse.Status
	(*HealthResponse)(nil),     // 1: health.v1.HealthResponse
	(*emptypb.Empty)(nil),      // 2: google.protobuf.Empty
}
var file_internal_interfaces_grpc_proto_health_proto_depIdxs = []int32{0}

func init() {
	file_internal_interfaces_grpc_proto_health_proto_init()
}
func file_internal_interfaces_grpc_proto_health_proto_init() {
	if File_internal_interfaces_grpc_proto_health_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_interfaces_grpc_proto_health_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_interfaces_grpc_proto_health_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_interfaces_grpc_proto_health_proto_goTypes,
		DependencyIndexes: file_internal_interfaces_grpc_proto_health_proto_depIdxs,
		EnumInfos:         file_internal_interfaces_grpc_proto_health_proto_enumTypes,
		MessageInfos:      file_internal_interfaces_grpc_proto_health_proto_msgTypes,
	}.Build()
	File_internal_interfaces_grpc_proto_health_proto = out.File
	file_internal_interfaces_grpc_proto_health_proto_rawDesc = nil
	file_internal_interfaces_grpc_proto_health_proto_goTypes = nil
	file_internal_interfaces_grpc_proto_health_proto_depIdxs = nil
}
